---
title: "Analysis"
---

As seen from the generated analyses, one can make several deductions regarding the debate between Messi and Ronaldo.

Firstly, let us analyse the timeplot showing the goals over seasons. Ronaldo has played 25 seasons so far and Messi has played 19 seasons. One could argue that Messi is better, because Messi's highest scoring season is above 70 goals, however Ronaldo did not break that number and his highest scoring season only had around 60 goals. However, Ronaldo had 2 seasons scoring 60 or more goals, but Messi only had the one season with more than 60 goals which was that one season. Ronaldo also had 1 more season where he scored more than 50 goals, with 6 while Messi had only 5, and Ronaldo had only 5 seasons in 25 seasons where he scored less than 20 goals, while Messi had 6 seasons scoring less than 20 goals. This shows that statistically, although Messi had the higer maximum, Ronaldo seems to be the better scorer across his career.

Secondly, from the goals by type plot, Ronaldo has scored in more different ways than Messi. He has scored more goals with his left foot than Messi has with his right foot, which shows that he has more goals with his weaker foot as compared to Messi. Ronaldo has also scored more goals with his head than Messi. These facts reinforce that Ronaldo is a more versatile goal scorer than Messi.

Next, we analyse the goals by position. Ronaldo has slightly over 200 goals from the Centre Forward Position, and over 400 goals from the Left or Right Wing, while Messi has over 250 goals from the Centre Forward and over 200 goals at Right Wing, and an almost negligible number of goals on the left. Though this might mean that Messi played less games on the left, it still shows that Ronaldo is a more versatile scorer because Ronaldo has more goals from the sides as compared to Messi with more goals through the middle, and it is technically harder to score from the sides.

We also analyse the goal distribution by the match minute through a heatmap. Ronaldo has scored more goals after the 90th minute and after, which shows that Ronaldo is a more clutch scorer because in the later stages of the game, players generally get more fatigued so it would be harder to score, so it takes a great scorer to score in the later stages of the game. However, both of them have a very high percentage of goals late into the game within 90 minutes, so both are clutch. However, it is also tough to compare that because within 90 minutes, the goals they scored may not necessarily be the winning goal if the score is 4-1 for example.
